### ISSUE TITLE
why a specialized implementation?

### ISSUE THREAD

**Issue by vv01f** [mbarkhau/sbk#1]
Why SSS especially for Bitcoin, what is the advantage compared to a general solution that could be applied to many secrets (passwords, other key material such as onion privkeys, pgp, ssh…)?

**Comment by mbarkhau** [comment]
The main reason is usability, which I think includes very clear and simple communication about the main use-case. Yes this can be used to derive secrets and keys for any purpose, and I'm open to extending the use cases beyond generating a seed for bitcoin wallets, but I think this is the most important short term use case and it makes sense in terms of marketing to communicate it that way.
